<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Manejo de Errores con Try - Catch - Finallly</title>
  </head>
  <body>
    <h1>Manejo de Errores con Try - Catch - Finally</h1>
    <script>
      try {
        console.log("En el try se agrega el codigo a evaluar");
        noExiste;
        console.log("Segundo mensaje en el try");
      } catch (error) {
        console.log("Catch, captura cualquier error surgido en el try" + error);
        // finally puede servir para finalizar una acción obligada.
      } finally {
        console.log(
          "El bloque finally se ejecutará siempre al final de un bloque try-catch"
        );
      }

      try {
        let number = "y";
        if (isNaN(number)) {
          //existen varios tipos de error - consultar MDN
          throw new Error("Please, put only numbers inside the inbox");
        }
        console.log(number * number);
      } catch (error) {
        console.log(`Error: ${error}`);
      } finally {
        console.log(
          "El bloque finally se ejecutará siempre al final de un bloque try-catch"
        );
      }
    </script>
  </body>
</html>
